# Update Suricata Rules from Emerging threats database.
# This script requires an inventory.yml and files/suricata.yaml file to work properly.
# Usage: Only used to update ET rules when a system has Suricata installed


- hosts: all
  remote_user: ##[[ADD SUDO USER HERE]]
  sudo: true
  tasks:

    - name: stop suricata daemon if it is running
      service: name=suricata state=stopped

    - name: download sources
      get_url: url=http://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz dest=/tmp/emerging.rules.tar.gz

    - name: Moving rules into Suricata primary directory
      unarchive: src=/tmp/emerging.rules.tar.gz dest=/etc/suricata/ copy=no

    - name: Starting suricata in Daemon mode on eth0. safe start mode.
      command: 'suricata -c /etc/suricata/suricata.yaml -i eth0 --init-errors-fatal -D'

    - name: Comment in SecurityAlerts on Hipchat
      hipchat: token=###################### [[Hipchat Token Here]] room=################# [[ Room token Here ]] color=green  msg="@here Suricata ET Rules were updated... Deploy complete!"
